Added contribution guidelines to CONTRIBUTING.md and demo images to assets folder.
Dacience/DataScientist pull request #42
Opened 2020-11-28 12:35 UTC by Pranav016

1. Added contribution guidelines to CONTRIBUTING.md and demo images to assets folder.

2. This pull request is a part of NJACK Winter of Code so please merge this after 1 Dec, 2020 so that it gets counted.

3. Solves issue #38 

4. Any suggestions for changes are always welcome.

2020-11-28 12:41 UTC, sidhu1012 commented on CONTRIBUTING.md
> +We are happy to welcome all the contributions from anyone willing to improve/add new scripts to this project. Thank you for helping out and remember, **no contribution is too small.**
No*. 'n' capital

2020-11-28 12:41 UTC, sidhu1012 commented on CONTRIBUTING.md
> +- Wait for the Issue to be assigned to you after which you can start working on it.
Shouldn't wait for issue to be assigned, just comment you are working on it if no one else is and get started.

2020-11-28 12:41 UTC, sidhu1012 commented on CONTRIBUTING.md
> +## Step 3 : Work on the issue assigned
'Assigned ' should not be used.

2020-11-28 12:41 UTC, sidhu1012 commented on CONTRIBUTING.md
> +- Work on the issue(s) assigned to you.
Here also , "assigned" and everywhere else too .

2020-11-28 12:42 UTC, sidhu1012 commented
This should also include steps to install the repo from github.

- In case of development.

- For usage.

2020-11-28 13:35 UTC, Pranav016 commented
Sure I'll make all the suggested changes.

2020-11-30 07:55 UTC, sidhu1012 commented on CONTRIBUTING.md
> +$ git remote add upstream https://github.com/<upstream-owner>/<repo-name>
Replace `<repo_name>` and similar instance with DataScientist repo name and link.

2020-11-30 07:55 UTC, sidhu1012 commented on CONTRIBUTING.md
> +
Environment setup shouldn't be completely focused on Anaconda but should be in general.

2020-11-30 08:32 UTC, Pranav016 commented
Made all the suggested changes 👍

2020-11-30 09:06 UTC, Pranav016 commented
@sidhu1012  Sorry Sir, the issue #39  was assigned to me and I had spent a couple of hours working on it and #45  pull request degrades the hours I spent. It is clearly mentioned on the Gitter channel that we have to check if the issue is assigned to someone else before working on it. Please look into it to make sure that the rules of NJACK are followed and decorum is maintained.

2020-12-01 06:44 UTC, sidhu1012 commented on CODE_OF_CONDUCT.md
> +* Showing empathy towards other community members
Add one more that one shoudn't adress with tiltes such as sir , mam etc and should adress by username.

2020-12-01 09:22 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +* Showing empathy towards other community members
Done 👍

2020-12-02 12:02 UTC, Pranav016 commented
@sidhu1012 I have made all the suggested changes for these issues. Do let me know if there are any other changes to be made so that I can get this pull request merged.  I'd be happy to improve it as much as I can :)

2020-12-02 12:08 UTC, sidhu1012 commented
> @sidhu1012 I have made all the suggested changes for these issues. Do let me know if there are any other changes to be made so that I can get this pull request merged.  I'd be happy to improve it as much as I can :)

Will review tomorrow!

2020-12-03 06:41 UTC, sidhu1012 commented on CODE_OF_CONDUCT.md
> +If you believe someone is violating the code of conduct, we ask that you report it by emailing [mailto:Daicience](<address here>).
Give my email handle here

2020-12-03 06:41 UTC, sidhu1012 commented on CONTRIBUTING.md
> +
Add pip install -e .

2020-12-03 06:41 UTC, sidhu1012 commented
Resolve these reviews , else LGTM!

2020-12-03 09:14 UTC, Pranav016 commented on CONTRIBUTING.md
> +
Is this command correct? `pip install -e git+https://github.com/sidhu1012/DataScientist.git`

2020-12-04 08:22 UTC, Pranav016 commented
@sidhu1012 Made all the suggested changes. Please merge this PR that solves issues #38 and #39. Thanks :)

2020-12-05 10:21 UTC, Pranav016 commented
@sidhu1012 Please merge this pull request, a lot of effort was put into this 💯 😄

2020-12-07 01:26 UTC, Pranav016 commented
@sidhu1012 Made all the suggested changes. Please merge this PR solving issues #38 and #39. Thanks :)

2020-12-07 05:47 UTC, sidhu1012 requested changes

2020-12-07 05:47 UTC, sidhu1012 commented on CONTRIBUTING.md
> +pip install -e requirements.txt
and

```
pip install -e .

2020-12-07 12:36 UTC, Pranav016 commented on CONTRIBUTING.md
> +pip install -e requirements.txt
Done 😄

2020-12-07 12:38 UTC, sidhu1012 requested changes

2020-12-07 12:38 UTC, sidhu1012 commented on CONTRIBUTING.md
> +pip install -e
still missing `.` . It should be `pip install -e .`

2020-12-07 12:43 UTC, Pranav016 commented on CONTRIBUTING.md
> +pip install -e
Sorry, had missed the `.`  
Fixed now 👍

2020-12-07 12:51 UTC, merged