random_forest_regression + test cases added
Dacience/DataScientist pull request #43
Opened 2020-11-29 18:12 UTC by shreyaspj20

2020-11-29 18:12 UTC, pep8speaks commented
Hello @shreyaspj20! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`datascientist/model/regression/skl/ensemble_model/random_forest_regression.py`](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py):

> [Line 9:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 11:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 13:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 79 characters)
> [Line 19:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py#L19): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 79 characters)
> [Line 20:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/random_forest_regression.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)

* In the file [`datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py`](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py):

> [Line 1:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py#L1): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 79 characters)
> [Line 14:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 20:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 26:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py#L26): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 31:80](https://github.com/Dacience/DataScientist/blob/e94071aa8df0188a92fb4011b1006185bd803174/datascientist/model/regression/skl/ensemble_model/tests/test_random_forest.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)

2020-11-30 07:47 UTC, sidhu1012 requested changes

2020-11-30 07:47 UTC, sidhu1012 commented on datascientist/model/regression/skl/ensemble_model/random_forest_regression.py
> +                              verbose=0, warm_start=False):
This is not the right way since function is missing some arguments.

https://github.com/Dacience/DataScientist/blob/5f1371303dcbbb6cbccf9b640b0f2e15f15e1818/datascientist/model/regression/skl/linear_model/baysianridge.py#L9

2020-11-30 07:47 UTC, sidhu1012 commented on datascientist/model/regression/skl/ensemble_model/random_forest_regression.py
> +    model_name = 'RandomForest'
`RandomForestRegressor`

2020-11-30 08:10 UTC, shreyaspj20 commented on datascientist/model/regression/skl/ensemble_model/random_forest_regression.py
> +    model_name = 'RandomForest'
changes done

2020-12-01 06:49 UTC, merged

2020-12-01 06:49 UTC, sidhu1012 commented
LGTM!

2020-12-01 06:58 UTC, shreyaspj20 commented
Can I now work on gradient boosting models like xgb, lgbm for regression??

2020-12-01 14:08 UTC, shreyaspj20 commented
Can I continue working on gradient boosting models under ensemble models folder??

2020-12-01 14:09 UTC, sidhu1012 commented
> Can I continue working on gradient boosting models under ensemble models folder??

Yes keep going!